[package]
name = "flan_gb_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
rand = "0.8.5"
mini_gl_fb = "0.9.0"
rodio = "0.15.0"
